### ISSUE TITLE
Error in registering MaxPoolWithArgmax

### ISSUE THREAD

**Issue by vernwalrahul** [tkuanlun350/Tensorflow-SegNet#11]
while running the python file, following error turns up:
![screenshot from 2017-07-30 01-00-27](https://user-images.githubusercontent.com/23414388/28747679-8794186a-74c2-11e7-95d2-c30d1a96cd37.png)

**Comment by tkuanlun350** [comment]
Sorry, this issue should be fixed now. Feel free to reopen if you encountered any problem.

**Comment by tom-bu** [comment]
I'm get the same error. Is it because I'm using python3?

```python
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import model
  File "/Users/Tommy/Applications/SegNet/Tensorflow-SegNet/model.py", line 20, in <module>
    @ops.RegisterGradient("MaxPoolWithArgmax")
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1788, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'MaxPoolWithArgmax' !(Previous registration was in _find_and_load_unlocked <frozen importlib._bootstrap>:955)"
```
