### ISSUE TITLE
Trying to implement my dataset

### ISSUE THREAD

**Issue by ShadowRawal** [tkuanlun350/Tensorflow-SegNet#49]
Traceback (most recent call last):
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[{{node shuffle_batch}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    tf.app.run()
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 49, in main
    model.training(FLAGS, is_finetune=False)
  File "/home/svarma/rahul/Tensorflow-SegNet-master/model.py", line 395, in training
    image_batch ,label_batch = sess.run([images, labels])
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[node shuffle_batch (defined at /home/svarma/rahul/Tensorflow-SegNet-master/Inputs.py:44) ]]

Caused by op 'shuffle_batch', defined at:
  File "main.py", line 52, in <module>
    tf.app.run()
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 49, in main
    model.training(FLAGS, is_finetune=False)
  File "/home/svarma/rahul/Tensorflow-SegNet-master/model.py", line 357, in training
    images, labels = CamVidInputs(image_filenames, label_filenames, batch_size)
  File "/home/svarma/rahul/Tensorflow-SegNet-master/Inputs.py", line 120, in CamVidInputs
    shuffle=True)
  File "/home/svarma/rahul/Tensorflow-SegNet-master/Inputs.py", line 44, in _generate_image_and_label_batch
    min_after_dequeue=min_queue_examples)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 1346, in shuffle_batch
    name=name)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 873, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/svarma/anaconda3/envs/my_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[node shuffle_batch (defined at /home/svarma/rahul/Tensorflow-SegNet-master/Inputs.py:44)

------------------------------------------------------------------------------------------------------------------------
This is the error I am facing.
following are the changes I have done-
epochs = 10
classes = 2.
test data = 16
train data = 17
val data = 11

**Comment by lgw9705** [comment]
I have the same problem. Did you clear this problem?
